on:
  workflow_call:
    inputs:
      python-version:
        type: "string"
        required: false
        default: "3.11"

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: .pre-commit-config.yaml
        check-latest: true
    - name: pre-commit cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: >-
          ${{ runner.os }}
          -pre-commit
          -${{ inputs.python-version }}
          -${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-${{ inputs.python-version }}
          ${{ runner.os }}-pre-commit
    - run: python3 -m pip install --upgrade pre-commit
    - run: pre-commit run --all-files --show-diff-on-failure
